# Update for your relative path
path : /Users/guillaume/Downloads/Imperial/Spring/GDP/projectWB/Database/DataLayer1
train: images/train
val: images/valid

names: 
  0 : car
  1 : traffic light
  2 : traffic sign
  3 : tree