
path : /Users/fredericdai/Desktop/Projet/oidv7/dataset/dataset1
train: images/train
val: images/val

names: 
  # 0 : bikelane
  # 1 : central_hatch
  # 2 : crossing
  # 3 : phy_med
  # 4 : pole
  # 5 : pro_bikelane
  # 6 : pro_sidewalk
  # 7 : safety_bar
  # 8 : sidewalk
  0 : car
  1 : traffic light
  2 : traffic sign
  3 : tree
