
#Path to Dataset : The dataset need to be as 

path : /path/to/dataset
train: images/train
val: images/val
#test: images/test #optional

names: 
  0 : class_0
  1 : class_1
  2 : class_2
  3 : class_3